image: 'rust:latest'

stages:
  - test

before_script:
  - rustup install nightly

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo +nightly test --verbose

cache:
  paths:
    - apt/
    - cargo/
    - target/